# Generated by Django 4.1.5 on 2023-04-30 22:24


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('day', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(default='No', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(default='', max_length=100)),
                ('review', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=15.0, max_digits=7)),
                ('subject', models.CharField(default='', max_length=256)),
                ('rating', models.FloatField(default=0.0)),
                ('numRatings', models.IntegerField(default=0)),
                ('availability', models.TextField(blank=True, default='')),
                ('profile_pic', models.ImageField(default='Headshot_PlaceHolder.png', null=True, upload_to='images/')),
                ('acceptedReqests', models.ManyToManyField(blank=True, related_name='accepted', to='tutoroos.request')),
                ('courses', models.ManyToManyField(blank=True, to='tutoroos.course')),
                ('pendingRequests', models.ManyToManyField(blank=True, related_name='pending', to='tutoroos.request')),
                ('reviews', models.ManyToManyField(blank=True, to='tutoroos.review')),
            ],
        ),
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=256)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoroos.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pendingRequests', models.ManyToManyField(blank=True, to='tutoroos.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoroos.student'),
        ),
        migrations.AddField(
            model_name='request',
            name='Tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoroos.tutor'),
        ),
        migrations.AddField(
            model_name='request',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutoroos.course'),
        ),
    ]
