# Generated by Django 4.1.5 on 2023-05-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoroos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
